- name: installing mysql
  hosts: mysql
  become: yes
  vars: 
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: install mysql library
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"    
      login_host: mysql-giri.shrihan.fun
    register: mysql_info
    ignore_errors: true


  - name: print the output
    ansible.builtin.debug:
      msg: "mysql_info: {{ mysql_info }}"  

  - name: set up root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true      