- name: installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
      