- name: installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql library
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1    
      login_host: mysql-giri.shrihan.fun
    register: mysql_info
    ignore_errors: true


  - name: print the output
    ansible.builtin.debug:
      msg: "mysql_info: {{ mysql_info }}"    